### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by piotrgulbis** [drehimself/tailwindcss-tables#1]
Is it possible to still use the tailwind border classes? I can't seem to be able to assign "border-2 border-black" to any table elements to get it to work.

I've hidden all the table borders by setting the color to the same color as my background, but it feels like a dirty hack.

For example I don't want the table to have any borders, but I want there to be a border under the table head.

**Comment by drehimself** [comment]
Tailwind border classes still seem to work. They won't apply on the border bottoms/border tops since those are more specific (the defined bootstrap styles). 

A slightly less hacky way to remove the borders:

```css
.table td {
  border-bottom: 0;
}
.table td, .table th {
  border-top: 0;
}
```

I'll look into adding a config option for this use case, since it seems useful.

**Comment by piotrgulbis** [comment]
Great stuff dre! Thank you!
