### ISSUE TITLE
Change the vertical-align: top;

### ISSUE THREAD

**Issue by simonj** [drehimself/tailwindcss-tables#2]
Thanks for a nice packages.

How can i change the `    vertical-align: top;` to `    vertical-align: middle;`

<img width="298" alt="skaermbillede 2018-07-27 kl 12 01 35" src="https://user-images.githubusercontent.com/183790/43314959-d54cfcbc-9194-11e8-8ec1-5841f0577aab.png">

**Comment by drehimself** [comment]
The best way would be to just override it in your own css file. You might have to stick an `!important` on it as well.

**Comment by simonj** [comment]
I can't do that in the tailwindcss config where i import the package :)? @drehimself
