### ISSUE TITLE
Un-wanted Border on top and right side

### ISSUE THREAD

**Issue by shaqaruden** [drehimself/tailwindcss-tables#3]
I found this issue when putting the table on top of a colored background.  I was able to remove the top border by applying a border-top: 0; style to each of the header th tags

`<th style="border-top: 0" scope="col">#</th>`

I was not able to find where the border or space on the right side was coming from. Image below depicts both borders

![image](https://user-images.githubusercontent.com/5414897/47832146-2e6d7f80-dd6a-11e8-9d99-0f8eb33bee94.png)

**Comment by drehimself** [comment]
Hey, sorry for the super late reply. I haven't look at this repo in months.

Are you using `<table class="table table-bordered>`?

If so, don't use `.table-bordered` it does add the right border as in your screenshot.

I'm able to reproduce your screenshot without using `.table-bordered` and the right border is gone. You can remove the top border like you did: 
![table](https://user-images.githubusercontent.com/4316355/59162509-46576f80-8ac0-11e9-8f68-e471dfa99d17.png)
