### ISSUE TITLE
Does not seem to be compatible with Tailwind 1.0+

### ISSUE THREAD

**Issue by shaqaruden** [drehimself/tailwindcss-tables#6]
Styles don't seem to work with tailwind 1.0+. Plugin was brought in via yarn.

![image](https://user-images.githubusercontent.com/5414897/61255024-dda18980-a734-11e9-972a-cc55e6a11572.png)

**Comment by drehimself** [comment]
What type of project are you using tailwind with? I've tried it with vue-cli 3 and nuxt and both seem to work fine with Tailwind v1
